### ISSUE TITLE
Spout2 inputs do not work in Studio Mode

### ISSUE THREAD

**Issue by Tossrock** [Off-World-Live/obs-spout2-plugin#17]
When running in Studio Mode, Spout2 inputs don't render properly in the Preview panel. This makes it difficult to compose scenes in advance during a broadcast.

Here's a video demonstrating the behavior. I have two scenes, one which is the water bubbles is a Media Source, the other is a Spout2 input. When the Spout2 Input is in the preview pane, it doesn't render. However, once it transitions to the Program pane, it is rendered.

https://youtu.be/YtcoCaWmpjE

**Comment by campbellwmorgan** [comment]
This this is related to #15
