### ISSUE TITLE
Please can add spot video out per scene?

### ISSUE THREAD

**Issue by Groboto** [Off-World-Live/obs-spout2-plugin#25]
Will be very useful if can add spout output  per scene, as with NDI,  where you can output video from scene to NDI.
I mean, is possible send video only of the whole scene stand alone.
Spout plugin only can send the main output. 
With NDI plugin, you can add dedicated NDI output as a filter on the capture device, will be nice see same feature with spout plugin, please!
Thanks for your great work!!

**Comment by campbellwmorgan** [comment]
Hi glad you are enjoying this. We have started work on the filter and hope to have that out some time soon. It is on our roadmap. We will let you know when it's out!

**Comment by Groboto** [comment]
That will be awesome!! I cant wait more for put my hands on that filter :)

**Comment by Groboto** [comment]
Apologize for this question, when this feature will be availble on release?
I dont have idea how compile myself.... : (

**Comment by campbellwmorgan** [comment]
@Groboto we're going to thoroughly QA it early next week and then release once we're sure it's got no bugs. It's true that compilation is a massive PITA.

**Comment by Groboto** [comment]
Thanks so much for reply, really appreciated !
I stay here waiting :)   Im so happy!!!

**Comment by campbellwmorgan** [comment]
@Groboto here it is! Let us know if you find any bugs https://github.com/Off-World-Live/obs-spout2-plugin/releases/tag/v1.2
