### ISSUE TITLE
Spout Filter  bugs.

### ISSUE THREAD

**Issue by Groboto** [Off-World-Live/obs-spout2-plugin#34]
Hello Guys, here the first bugs to report.
Bug 1-When add Spout and NDI filters to scene , both at same time,  crash happen when when close OBS software .
Here  a crash report.
[Crash 2021-08-18 14-10-00.txt](https://github.com/Off-World-Live/obs-spout2-plugin/files/7008991/Crash.2021-08-18.14-10-00.txt)

Bug 2- I disable Spout filter clicking on the eye at left of the filter, spout filter not is disable and continue receiving video sent by the filter. This is a minor issue for sure.

Both bugs have lower severity, where probably the bug 1 is the most important.
Also when this problems happens is superb have this feature!! and work super stable with just exception of this 2 minor bugs.
Congratulations!

Tested on:  OBS 27.0.1  x64, WINDOWS 10

Let me know if need more info!

**Comment by campbellwmorgan** [comment]
Thanks a lot for taking the time to report. We'll investigate and see if we can replicate both and come back to you if we can't!

**Comment by campbellwmorgan** [comment]
Hi @Groboto could you try this release https://github.com/Off-World-Live/obs-spout2-plugin/releases/tag/v1.6-beta to see if it fixes your crash (fyi this is for OBS 28)

**Comment by campbellwmorgan** [comment]
Closing until more feedback received
