### ISSUE TITLE
Spout2 For Slobs

### ISSUE THREAD

**Issue by KitBallard64** [Off-World-Live/obs-spout2-plugin#37]
I guess this is a bug? I attempted to install this into Slobs and doesn't seem to be integrating with it. Unless there's som'in slightly different under the hood that is preventing Obs Plugins working, I do have a plugin installed already (OpenVR Capture), so I'm unsure if I'm doing anything wrong. You can see below that it's not there (unless I'm a blind heck)
![image](https://user-images.githubusercontent.com/19273132/155115040-701c8683-16a1-4f44-a094-18ec4bd1ef60.png)

If there's nothing that can be done, that's ok. I appreciate the work and support at the very least.
~Kit

**Comment by campbellwmorgan** [comment]
Hi @KitBallard64 Thanks a lot for the bug report. Sadly Stream Labs OBS isn't really obs, but instead a whole lot of javascript wrapping libobs (the C library) underneath. This means that OBS plugins don't work on SLOBS unless SLOBS explicitly choose to integrate it. We have been in touch with them about this over the last year and a bit and it seems they have no intention of integrating it. By all means, please get in touch with them yourself as we would love this plugin to work with streamlabs!

**Comment by KitBallard64** [comment]
Rats. ok, I appreciate the quick response. Good luck on the project!
