### ISSUE TITLE
Removing Spout filter crashes OBS Studio

### ISSUE THREAD

**Issue by Xaymar** [Off-World-Live/obs-spout2-plugin#41]
**Describe the bug**
A crash is observed when a Spout filter is added to any video source and removed from it. This crash happens without any Spout clients connected.

**To Reproduce**
1. Add any video source.
2. Add a spout filter to the source.
3. Remove the spout filter from the source.
4. Crash.

**Expected behavior**
No crash.

[2022-04-12 09-32-08.txt](https://github.com/Off-World-Live/obs-spout2-plugin/files/8470644/2022-04-12.09-32-08.txt)
[Crash 2022-04-12 09-46-45.txt](https://github.com/Off-World-Live/obs-spout2-plugin/files/8470639/Crash.2022-04-12.09-46-45.txt)

**Screenshots**

**About the Software:**
 - OBS Version 27.2.4
 - OBS Spout 2 Source Plugin Version 1.3

**About Your Machine :**
 - OS: Windows 10 Pro
 - GPU NVIDIA RTX 3090
 - NVidia Driver Version 30.0.15.1215
 - RAM 16GB
 - Machine Type Desktop
 - Battery Mode has no battery
 

**Additional context**

**Comment by campbellwmorgan** [comment]
@Xaymar thanks for this report. Looks similar to #40

**Comment by Xaymar** [comment]
@campbellwmorgan Looking at the crash logs in #40, this appears to be a different crash. Unfortunately I have not spent any time debugging the plugin to say for sure if it is the same or a different one.

**Comment by campbellwmorgan** [comment]
@Xaymar could you try https://github.com/Off-World-Live/obs-spout2-plugin/releases/tag/v1.6-beta to see if it resolves your crash issue

**Comment by Xaymar** [comment]
Currently can't test due to OBS Studio 28.0.x being incredibly unstable even without any plugins installed. I've downgraded to 27.2.4 again, which was the last known stable version of OBS Studio for my system.

**Comment by flaeri** [comment]
I had a very similar (identical?) crash ([spoutCrash.txt](https://github.com/Off-World-Live/obs-spout2-plugin/files/9695665/spoutCrash.txt)), with the same repro steps.

Using the new beta you suggested I can no longer get it to crash by deleting the spout filters.
This was on OBS 28.0.3.

**Comment by Xaymar** [comment]
@campbellwmorgan That version does not appear to load in any OBS Studio version I have.

```
06:06:18.045: LoadLibrary failed for '../../obs-plugins/64bit/win-spout.dll': The specified module could not be found.
06:06:18.045:  (126)
06:06:18.046: Module '../../obs-plugins/64bit/win-spout.dll' not loaded
```

**Comment by Xaymar** [comment]
I've built the plugin from source at the specified version, and it appears to fix the issue.
