### ISSUE TITLE
Does not load in OBS 28

### ISSUE THREAD

**Issue by crystall1nedev** [Off-World-Live/obs-spout2-plugin#43]
**Describe the bug**
Title says it all. OBS 28 doesn't let it load 

**To Reproduce**
1. Install OBS 28 beta 1
2. Install obs-spout2-plugin
3. Run OBS

**Expected behavior**
Expected it to work (not really, OBS 28 marks some pretty big changes)

```
22:44:48.959: Skipping module '../../obs-plugins/64bit/Spout.dll', not an OBS plugin
22:44:48.981: Skipping module '../../obs-plugins/64bit/SpoutDX.dll', not an OBS plugin
22:44:49.004: Skipping module '../../obs-plugins/64bit/SpoutLibrary.dll', not an OBS plugin
22:44:49.306: Skipping module '../../obs-plugins/64bit/win-spout.dll' due to possible import conflicts
```

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/55281754/182751597-91078736-aa28-476f-ba38-d72890a7dce9.png">

**About the Software:**
 - OBS Version: [28.0.0-beta1, commit 4a64b2a](https://github.com/obsproject/obs-studio/tree/28.0.0-beta1)
 - OBS Spout 2 Source Plugin Version: 1.3

**About Your Machine :**
 - OS: Windows 11 Pro for Insiders, build 25163
 - GPU: AMD Radeon Pro Vega 20
 - Driver Version: 21.40.23.07-220125a-376255E-RadeonSoftware
 - RAM: 32GB
 - Machine Type: MacBook Pro (15-inch, 2018) 
 - Battery Mode: Battery + Plugged in

**Comment by campbellwmorgan** [comment]
Hi Thanks for this. We'll do a build for the latest obs as soon as we can and update this ticket when released. Thanks for letting us know it was out :)

**Comment by crystall1nedev** [comment]
No problem, great work by the way!

**Comment by Xaymar** [comment]
Any plans of releasing a "Beta" version for the 28.0.0-rc1 release?

**Comment by campbellwmorgan** [comment]
@Xaymar generally speaking we only target the official releases as the release candidate releases tend to continue coming out and require rebuilds from us. However if we do manage a build before then we'll notify on this thread

**Comment by Xaymar** [comment]
Normally libOBS keeps backwards compatibility from the first Release Candidate to the final version, which is how StreamFX has been able to support the latest OBS Studio versions ahead of them being released with no update being necessary from StreamFX itself.

I'm looking forward to the build. At the moment the lack of obs-spout2 has resulted in me falling back to NDI and Virtual Cameras, which have significantly higher overhead than Spout2.

**Comment by Xaymar** [comment]
Works great!
