### ISSUE TITLE
Spout media freezing in UE when OBS isn't in focus?

### ISSUE THREAD

**Issue by LordGrym** [Off-World-Live/obs-spout2-plugin#47]
Hello

I am spouting video footage from OBS 28.0.2 to UE 5.03. Comes through good when OBS is in focus but when I click on UE the media will freeze in there after a moment. I end up having to restart OBS completely or destroy and recreate the spouts in OBS to get it back. 

I tried again and left OBS in focus and it ran fine for a good solid 10 minutes or so. But as soon as I put UE in focus the media will freeze. This is with OBS running both in normal and Admin mode.

The current stable Spout release works completely fine, so I am not too sure what's going on.

I hope this video helps a bit. Please let me know if there is anything I am missing here, or anything I can do to help.
https://www.dropbox.com/s/zq611rnjxp64gsl/SpoutIssue.mp4?dl=0

Thanks.

**Comment by LordGrym** [comment]
Sorry, I should mention this is for the Spout Fix Beta 1.6 release.

**Comment by campbellwmorgan** [comment]
Hi, Thanks very much for this report. We'll try to reproduce locally. If you wouldn't mind, in order for us to try to isolate the issue (ie to check whether the bug is Unreal or OBS), please could you try using this https://github.com/leadedge/Spout2/blob/master/DEMO/SpoutReceiver.exe and OBS to see if you can replicate the freeze.

Many thanks

**Comment by LordGrym** [comment]
Awesome. Gave it a whirl and no freezing in that receiver. Here is a video of it https://www.dropbox.com/s/xdckb6r6niyoppg/SpoutTest.mp4?dl=0

Been running after this video for a solid 10 minutes with no issues either.

In my project I have about 4 or 5 different spouts running into UE. So what i did was deleted all of them except for the one on this media source, tested again in UE and it still froze, so that tells me the other spouts and using multiple spouts isn't the problem either.

Just tried this in a blank project and got the freeze there too https://www.dropbox.com/s/e7d7n2it3v6a4sv/SpoutBlankProject.mp4?dl=0

**Comment by LordGrym** [comment]
Yo @campbellwmorgan was just testing out the 1.7 release for OBS 29. Getting this same issue here with that one too. I can keep using the OBS 28 release, but just thought I'd let you know!

If it helps at all, some more info. Both me and another person working in same project, happens on both our machines. Running UE 5.0.3 + DLSS + DirectX 11

**Comment by campbellwmorgan** [comment]
@LordGrym https://github.com/Off-World-Live/obs-spout2-plugin/releases/tag/v1.8-alpha

**Comment by LordGrym** [comment]
@campbellwmorgan mate, you guys are f$@n legends. Can confirm that the spout media is **no longer** freezing in UE. Haven't given it a long time to test. But on initial play, with 4 different spouts from OBS, everything is moving and buttery smooth.

Thankyou so much for doing this!

**Comment by campbellwmorgan** [comment]
@LordGrym Great to hear! It's been @millenium-cyborg who's solved this so I can't take credit!

**Comment by campbellwmorgan** [comment]
hey @LordGrym really sorry to say that we've still managed to recreate the freezing in QA so we're not quite there yet. Hopefully some good news very soon :)

**Comment by LordGrym** [comment]
@campbellwmorgan thanks for the heads up, I just jumped in and got an instant freeze too haha. No problem! Looking forward to it 😄

**Comment by campbellwmorgan** [comment]
@LordGrym I think @millenium-cyborg has done it - i can no longer recreate the freeze with this build https://github.com/Off-World-Live/obs-spout2-plugin/releases/tag/v1.8-beta-2 - let us know!

**Comment by campbellwmorgan** [comment]
@LordGrym Our QA suggests that this release https://github.com/Off-World-Live/obs-spout2-plugin/releases/tag/v1.8 has fixed this bug. I'm closing the issue now, but feel free to re-open if the problem re-appears for you.

**Comment by LordGrym** [comment]
@campbellwmorgan & @millenium-cyborg thanks a ton for this. Looks like its working really well, no freezes yet either. Real test will be during the 4 hour stream tomorrow. So stoked you guys were able to sort the issue. Very grateful for the work put into it, you guys rule!
