### ISSUE TITLE
is it possible to use it with OBS v29.0.0 on windows? how to? (not v28). Thanks

### ISSUE THREAD

**Issue by turkodamian2** [Off-World-Live/obs-spout2-plugin#51]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by campbellwmorgan** [comment]
Hi, The OBS 28 version works fine with 29, but I have just released another build against 29 just to be sure!
