### ISSUE TITLE
VTuber model disappeared into the abyss

### ISSUE THREAD

**Issue by CrawfordK** [Off-World-Live/obs-spout2-plugin#60]
**Describe the bug**
Just installed this and it showed my model and duplicated it until there was nothing left on the screen. Now when i restart OBS and switch to the scene with the source it does a weird duplication that fades out.

**To Reproduce**
1. Select the scene with the source

**Expected behavior**
Show my vtuber without the vtube studio settings overlay.

https://obsproject.com/logs/aFYlzWi4nd5xNEut

**Screenshots**
https://i.imgur.com/6Hmi4Fe.gif

**About the Software:**
 - OBS Version 29.1.2 (se.live)
 - OBS Spout 2 Source Plugin Version v1.8

**About Your Machine :**
 - OS: Windows 10 Pro
 - GPU: Nvidia RTX 1080
 - GPU Driver Version: 531.41
 - RAM: 32GB
 - Machine Type: Desktop (custom)
 - Battery Mode: Plugged in
  

**Additional context**
This is my first time using this and installing it, it's currently installed in my **Program Files/obs-studio** folder.

**Comment by CrawfordK** [comment]
Just want to update that I can get it to work with Spout Sender Demo.

**Comment by CrawfordK** [comment]
Issue resolved. I can see the VTube Studio option in the senders now.

**Comment by campbellwmorgan** [comment]
@CrawfordK Good to hear! Thanks
